### ISSUE TITLE
Normalize booleans sent back from info()

### ISSUE THREAD

**Issue by bschlenk** [bschlenk/node-roku-client#200]
`client.info()` returns booleans as strings ("true"/"false"), but it'd be nice if they were returned as actual booleans. This would be a breaking change.

**Comment by RubyRubenstahl** [comment]
Since the method doesn't currently take any arguments, you could accept an opts argument with something like `client.info({nomalize: true})`, allowing you to opt into normalization without breaking anything.

**Comment by bschlenk** [comment]
Thanks for the suggestion @RubyRubenstahl! I started going down that path, but it'll be hard to get the TS types to work correctly with that approach, since the return values would all have to be typed as `string | boolean`. Decided to [strongly type the whole object](https://github.com/bschlenk/node-roku-client/commit/db9fc48d8570f559077e25025ef672206107bc88) instead, which will be released with v5.

**Comment by bschlenk** [comment]
This was released with v5.0.0.
